# fly.toml app configuration file generated for post-anything-you-like on 2024-01-28T16:20:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'post-anything-you-like'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
